# Generated by Django 3.1.7 on 2021-03-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='print',
            new_name='price',
        ),
    ]
